dataset_path: "json"
dataset_kwargs:
  data_files:
    test: "/nfs/datasets/MedXpertQA/MM/test.jsonl"
task: medxpert_fewshot
test_split: test
fewshot_split: fewshot
# fewshot_split: val
output_type: generate_until
doc_to_visual: !function utils.medxpert_doc_to_visual
doc_to_text: !function utils.medxpert_doc_to_text
doc_to_answer: !function utils.medxpert_doc_to_answer
doc_to_target: "label"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.medxpert_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: medxpert_perception_score
    aggregation: !function utils.medxpert_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  - version: 0.0
