task: "infovqa_val_fewshot"
test_split: validation
training_split: validation
output_type: generate_until
metric_list:
  - metric: anls
    aggregation: mean
    higher_is_better: true
include: _default_template_infovqa_yaml