dataset_path: "json"
dataset_kwargs:
  data_files:
    val: "/nfs/datasets/imagenet1k/val_Imagenet100_zs.json"
    # train: "/nfs/datasets/imagenet1k/fewshot_imagenet100_200samples.json"
  # From_YouTube: True
task: imagenet100
test_split: val
# fewshot_split: val
output_type: generate_until
doc_to_visual: !function utils.imagenet100_doc_to_visual
doc_to_text: !function utils.imagenet100_doc_to_text
doc_to_target: "answer"
generation_kwargs:
  max_new_tokens: 32
  temperature: 0
  top_p: 1.0
  num_beams: 1
  do_sample: false
# The return value of process_results will be used by metrics
process_results: !function utils.imagenet100_process_results
# Note that the metric name can be either a registed metric function (such as the case for GQA) or a key name returned by process_results
metric_list:
  - metric: imagenet100_perception_score
    aggregation: !function utils.imagenet100_aggregate_results
    higher_is_better: true

lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""

metadata:
  - version: 0.0
